principal:
    resource: "@PrincipalBundle/Controller/"
    type:     annotation
    prefix:   /

rural:
    resource: "@RuralBundle/Controller/"
    type:     annotation
    prefix:   /rural

app:
    resource: '@AppBundle/Controller/'
    type: annotation
